server:
  port: 8765
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myzlsoft?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  # 实体类的存放路径
  type-aliases-package: com.zlsoft.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  file: ../logs/spring-boot-hello.log
  level.org.springframework.web: DEBUG